FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# one0x

Polls is a simple API allowing consumers to view polls and vote in them.

## Questions Collection [/questions]

### List All Questions [GET]

+ Response 200 (application/json)

        [
            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 2048
                    }, {
                        "choice": "Python",
                        "votes": 1024
                    }, {
                        "choice": "Objective-C",
                        "votes": 512
                    }, {
                        "choice": "Ruby",
                        "votes": 256
                    }
                ]
            }
        ]

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
/*
Replacing KarmaCoin...
  ... 0x6e43a69406dbe34a97aabc22e6f4fdc3450ab5e832dc201298fb965f7797d373
  KarmaCoin: 0x345ca3e014aaf5dca488057592ee47305d9b3e10
  Replacing GyanCoin...
  ... 0x5b4c4817de9ede70ce327b9a45aea5074033faa07999857f30aef4f340ecef87
  GyanCoin: 0xf25186b5081ff5ce73482ad761db0eb0d25abfbf
  Replacing ScholarshipContract...
  ... 0xffe25b214c0ff5419fa11eacf2990c422b43a6291e124b7a95284e465746fa8e
  ScholarshipContract: 0x8f0483125fcb9aaaefa9209d8e9d7b9c8b9fb90f
  Replacing QuestionContract...
  ... 0x5ddc9aa39c3f314568dd8149efa04045cc085db47c190c841ff3fce5dfdad46a
  QuestionContract: 0x9fbda871d559710256a2502a2517b794b482db40
  Replacing CollectionContract...
  ... 0xbcd216317ecc6fa189c8b737820ec63079d110f902724ebf1cdf019eadc78a23
  CollectionContract: 0x2c2b9c9a4a25e24b174f26114e8926a9f2128fe4

*/
